#!/usr/bin/env bash
# Deploy the IBC Eureka EVM contracts to the running eth-devnet enclave via
# DevnetDeploy.s.sol, and write the result to $DEVNET_DIR/deploy.env in the
# exact variable names devnet/lib/{config.js,lib.js} read: ICS26_ROUTER,
# ICS20_TRANSFER (NOT the ETH_ROUTER/ETH_ICS20 names that ended up hand-typed
# into devnet.env in an earlier manual run of this — those are never read by
# any of the JS/Python tooling, so a client silently talking to the wrong
# contract there was a real risk).
#
# NOTE: this deploys a brand-new AccessManager/ICS26Router/ICS20Transfer/
# verifier set every time it runs; it does not detect or reuse a prior
# deployment. Re-running it is *safe* (it never touches an existing
# deployment) but not a no-op — each run costs gas and produces new
# addresses, overwriting deploy.env.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
source "$SCRIPT_DIR/lib/common.sh"

ENCLAVE="${ENCLAVE:-eth-devnet}"
SIBE_HOME_DIR="${SIBE_HOME:-$HOME/solidity-ibc-eureka}"
IBC_SOLIDITY="$SIBE_HOME_DIR/ibc-solidity"

require_cmd kurtosis "run devnet/scripts/setup-toolchain.sh first."
require_cmd forge "run devnet/scripts/setup-toolchain.sh first."
require_dir "$IBC_SOLIDITY" "run devnet/scripts/setup-eureka-checkout.sh first."

DEVNET_DIR="$(resolve_devnet_dir)"
mkdir -p "$DEVNET_DIR"

# --- inputs --------------------------------------------------------------
log "resolving GETH_RPC"
GETH_RPC="$(kurtosis port print "$ENCLAVE" el-1-geth-lighthouse rpc 2>/dev/null | tr -d '\r')"
[ -n "$GETH_RPC" ] || die "kurtosis port print $ENCLAVE el-1-geth-lighthouse rpc returned nothing — is the enclave up? (kurtosis enclave ls)"
RPC_URL="$GETH_RPC"; case "$RPC_URL" in http*) ;; *) RPC_URL="http://$RPC_URL" ;; esac

log "resolving deployer key"
DEPLOYER_PK="$("$SCRIPT_DIR/get-deployer-key.sh")"

# --- vendor the script into the checkout (deploy/README.md) --------------
# DevnetDeploy.s.sol uses relative imports into the ibc-solidity contract
# tree, so it can only be compiled from inside that checkout.
SRC="$DEVNET_ROOT/deploy/DevnetDeploy.s.sol"
DEST="$IBC_SOLIDITY/scripts/DevnetDeploy.s.sol"
require_file "$SRC"
mkdir -p "$(dirname "$DEST")"
if [ -f "$DEST" ] && cmp -s "$SRC" "$DEST"; then
  ok "DevnetDeploy.s.sol already vendored into the checkout"
else
  cp "$SRC" "$DEST"
  ok "vendored DevnetDeploy.s.sol -> $DEST"
fi

# --- deploy ----------------------------------------------------------------
log "running forge script (broadcast to $RPC_URL)"
out="$(cd "$IBC_SOLIDITY" && forge script scripts/DevnetDeploy.s.sol:DevnetDeploy \
  --rpc-url "$RPC_URL" --private-key "$DEPLOYER_PK" --broadcast 2>&1)" \
  || { echo "$out"; die "forge script failed; see output above"; }
echo "$out"

result_line="$(grep -oE 'DEPLOY_RESULT \{.*\}' <<<"$out" | tail -n1)"
[ -n "$result_line" ] || die "did not find a 'DEPLOY_RESULT {...}' line in forge's output — deployment may have failed silently"
result_json="${result_line#DEPLOY_RESULT }"

require_cmd jq
ics26_router="$(jq -r '.ics26Router' <<<"$result_json")"
ics20_transfer="$(jq -r '.ics20Transfer' <<<"$result_json")"
access_manager="$(jq -r '.accessManager' <<<"$result_json")"
verifier_groth16="$(jq -r '.verifierGroth16' <<<"$result_json")"
verifier_mock="$(jq -r '.verifierMock' <<<"$result_json")"

for name_val in "ICS26_ROUTER=$ics26_router" "ICS20_TRANSFER=$ics20_transfer"; do
  case "${name_val#*=}" in
    0x*) ;;
    *) die "DEPLOY_RESULT missing or malformed field: $name_val (full json: $result_json)" ;;
  esac
done

cat > "$DEVNET_DIR/deploy.env" <<EOF
# Generated by devnet/scripts/deploy-contracts.sh — do not hand-edit.
# Re-running deploy-contracts.sh deploys a fresh set of contracts and
# overwrites this file with the new addresses.
ICS26_ROUTER=$ics26_router
ICS20_TRANSFER=$ics20_transfer
ACCESS_MANAGER=$access_manager
SP1_VERIFIER_GROTH16=$verifier_groth16
SP1_VERIFIER_MOCK=$verifier_mock
EOF

ok "wrote $DEVNET_DIR/deploy.env"
ok "ICS26Router=$ics26_router ICS20Transfer=$ics20_transfer"
