#!/usr/bin/env bash
# Write $DEVNET_DIR/ports.env from the live Kurtosis eth-devnet enclave.
# Must run before devnet/light-client/collect-instantiate-inputs.sh, which
# sources this file and fails with an unbound-variable error without it.
#
# Idempotent: always safe to re-run (e.g. after a container restart
# reassigns host ports — see devnet/README.md#the-evm-devnet-does-not-survive-a-restart).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
source "$SCRIPT_DIR/lib/common.sh"

ENCLAVE="${ENCLAVE:-eth-devnet}"

require_cmd kurtosis "run devnet/scripts/setup-toolchain.sh first."

DEVNET_DIR="$(resolve_devnet_dir)"
mkdir -p "$DEVNET_DIR"

log "reading ports from enclave '$ENCLAVE'"
BEACON="$(kurtosis port print "$ENCLAVE" cl-1-lighthouse-geth http 2>/dev/null | tr -d '\r')"
[ -n "$BEACON" ] || die "kurtosis port print $ENCLAVE cl-1-lighthouse-geth http returned nothing — is the enclave up? (kurtosis enclave ls)"

GETH_RPC="$(kurtosis port print "$ENCLAVE" el-1-geth-lighthouse rpc 2>/dev/null | tr -d '\r')"
[ -n "$GETH_RPC" ] || die "kurtosis port print $ENCLAVE el-1-geth-lighthouse rpc returned nothing — is the enclave up? (kurtosis enclave ls)"

cat > "$DEVNET_DIR/ports.env" <<EOF
# Generated by devnet/scripts/write-ports-env.sh — do not hand-edit.
# Re-run it after any enclave/container restart, which reassigns host ports.
BEACON=$BEACON
GETH_RPC=$GETH_RPC
EOF

ok "wrote $DEVNET_DIR/ports.env (BEACON=$BEACON GETH_RPC=$GETH_RPC)"
