// Config resolution for the devnet redemption scripts.
//
// Precedence, highest first:
//   1. process.env
//   2. devnet.env (next to this package, if present)
//   3. devnet.env.example defaults
//   4. the generated env files inside DEVNET_DIR (ports.env, cosmos.env,
//      deploy.env), which hold values produced by the devnet tooling itself
const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");

function parseEnvFile(file) {
  const out = {};
  if (!fs.existsSync(file)) return out;
  for (const line of fs.readFileSync(file, "utf8").split("\n")) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*?)\s*$/);
    if (m && !line.trim().startsWith("#")) out[m[1]] = m[2];
  }
  return out;
}

function load() {
  const defaults = parseEnvFile(path.join(ROOT, "devnet.env.example"));
  const local = parseEnvFile(path.join(ROOT, "devnet.env"));
  const cfg = { ...defaults, ...local };
  for (const k of Object.keys(cfg)) {
    if (process.env[k]) cfg[k] = process.env[k];
  }

  const devnetDir = cfg.DEVNET_DIR;
  if (!devnetDir || !fs.existsSync(devnetDir)) {
    throw new Error(`DEVNET_DIR does not exist: ${devnetDir}`);
  }

  // Values generated by the devnet tooling. They fill in anything still blank
  // but never override an explicit env var or devnet.env entry.
  const generated = {
    ...parseEnvFile(path.join(devnetDir, "ports.env")),
    ...parseEnvFile(path.join(devnetDir, "cosmos.env")),
    ...parseEnvFile(path.join(devnetDir, "deploy.env")),
  };
  for (const [k, v] of Object.entries(generated)) {
    if (!cfg[k]) cfg[k] = v;
  }
  if (!cfg.BEACON_URL && generated.BEACON) cfg.BEACON_URL = generated.BEACON;

  cfg.DEVNET_DIR = devnetDir;
  cfg.file = (name) => path.join(devnetDir, name);
  return cfg;
}

function require_(cfg, ...keys) {
  const missing = keys.filter((k) => !cfg[k]);
  if (missing.length) {
    throw new Error(
      `missing config: ${missing.join(", ")} — set them in devnet.env, in the ` +
      `environment, or make sure DEVNET_DIR (${cfg.DEVNET_DIR}) has the ` +
      `generated ports.env / cosmos.env / deploy.env`,
    );
  }
  return cfg;
}

module.exports = { load, require_, ROOT };
